---
- name: a playbook to setup my local machine with my basic customizations
  hosts: localhost
  connection: localhost
  become: yes
  roles:
   - install_vbox
  tasks:
   - name: install system updates for centos systems
     yum: name=* state=latest update_cache=yes
     when: ansible_distribution == "CentOS"

   - name: install system updates for ubuntu systems
     apt: upgrade=dist update_cache=yes
     when: ansible_distribution == "Ubuntu"