- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian bionic contrib
    state: present

   


- name: software installed
  apt:  pkg={{ item }} state=present update_cache=yes
  with_items:
    - screen
    - tmux
    - virtualbox-5.2
    - virtualbox-ext-pack
    